---
- hosts: all
  become: true

  vars:
    the_user: vagrant

  pre_tasks:

    - name: Upgrade system packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install base system packages
      apt:
        name: [
        'aptitude',
          'htop',
          'tree',
          'python-pip',
          'golang-go',
          'ruby',
          'build-essential',
          'curl',
          'file',
          'git',
          'python-setuptools',
          'apt-transport-https',
          'ca-certificates',
          'software-properties-common',
          'expect',
          'ubuntu-fan',
          'jq',
          'uuid-runtime',
          'maven'
         ]
        state: latest

    - name: Start the ssh agent
      lineinfile:
        path: "/home/{{ the_user }}/.bashrc"
        line: "eval `ssh-agent -s`"

    - name: Check if gcloud is installed
      command: gcloud -v
      register: gcloud_version_cmd
      ignore_errors: yes
    - set_fact:
        gcloud_installed: "{{ gcloud_version_cmd.rc == 0 }}"

  roles:

    - bash_profile

    - name: gcloud
      when: not gcloud_installed

    - travis_cli

